// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2TAnSwhCAhQhkm4icweeh90K6F_X-E04',
    appId: '1:513639776104:web:2a61ff4f30eb00dc2b20dd',
    messagingSenderId: '513639776104',
    projectId: 'rentandbuy-231d6',
    authDomain: 'rentandbuy-231d6.firebaseapp.com',
    storageBucket: 'rentandbuy-231d6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2TAnSwhCAhQhkm4icweeh90K6F_X-E04',
    appId: '1:513639776104:ios:dc518cc25dab95312b20dd',
    messagingSenderId: '513639776104',
    projectId: 'rentandbuy-231d6',
    storageBucket: 'rentandbuy-231d6.appspot.com',
    iosBundleId: 'com.example.rentAndBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2TAnSwhCAhQhkm4icweeh90K6F_X-E04',
    appId: '1:513639776104:web:96856ddd2a268f962b20dd',
    messagingSenderId: '513639776104',
    projectId: 'rentandbuy-231d6',
    authDomain: 'rentandbuy-231d6.firebaseapp.com',
    storageBucket: 'rentandbuy-231d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2TAnSwhCAhQhkm4icweeh90K6F_X-E04',
    appId: '1:513639776104:ios:dc518cc25dab95312b20dd',
    messagingSenderId: '513639776104',
    projectId: 'rentandbuy-231d6',
    storageBucket: 'rentandbuy-231d6.appspot.com',
    iosBundleId: 'com.example.rentAndBuy',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2TAnSwhCAhQhkm4icweeh90K6F_X-E04',
    appId: '1:513639776104:android:a3063d16efd4e33b2b20dd',
    messagingSenderId: '513639776104',
    projectId: 'rentandbuy-231d6',
    storageBucket: 'rentandbuy-231d6.appspot.com',
  );

}